[package]
name = "pmbot-strategy"
version = "0.1.0"
edition.workspace = true

[dependencies]
pmbot-core.workspace = true
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
anyhow.workspace = true
rust_decimal.workspace = true
rust_decimal_macros.workspace = true
statrs.workspace = true
chrono.workspace = true
serde.workspace = true
uuid.workspace = true
